### PR TITLE
Adds `identify` protocol

### PR DESCRIPTION
**Pull request by ralexstokes**
quick wip: needs more work before it is in a mergeable place

### CODE REVIEW

**Comment by aratz-lasa** [comment]
> quick wip: needs more work before it is in a mergeable place

What is it needed for getting mergeable?

**Comment by ralexstokes** [comment]
@aratz-lasa saw your question on gitter, thanks for your interest!

i want to merge #314 to set the stage for "default protocols" we may want (like `ping` or `identify`).

this PR was a quick hack to get a local instance of the node speaking `identify`. at the least we will want to clean this PR up before merging it in -- i think it would be worthwhile to spend some time thinking about how the public key is passed around and we should not keep the `Any` typing here: https://github.com/libp2p/py-libp2p/pull/297/files#diff-cbc6070f689b6fd50f9a26226bc4edcdR23

**Comment by ralexstokes** [comment]
working to merge in #314 and #315 and then a PR that sets `ping` as a default protocol.

alongside this work, want to merge in this `identify`.

**Comment by ralexstokes** [comment]
closing as future PRs have superseded this work

**Pull request closed without merging**
