### PR TITLE
Add links to the new bridged chats to README.md

### PR DESCRIPTION
**Pull request by swedneck**
matrix, discord, and IRC are all bridged together via matrix.

### CODE REVIEW

**Comment by ralexstokes** [comment]
the discord link is invalid -- can you update it please?

**Comment by swedneck** [comment]
@ralexstokes not sure what you mean, the discord link works fine for me.

**Comment by ralexstokes** [comment]
@swedneck if i try to accept the invitation it says the invite is invalid. do you see something different?

**Comment by swedneck** [comment]
@ralexstokes yeah the invite works like normal for me

**Comment by NIC619** [comment]
The invite works on my end.

**Comment by mhchia** [comment]
I think bridge chats are great. However, it seems they are not run by the official? I'm not sure if it is a good idea to list the non-official links in the badge section. cc @raulk @mgoelzer

**Comment by mgoelzer** [comment]
I agree that putting anything in as a badge gives the impression the project officially recognizes it.  I'm kind of inclined to do it anyway, wait and see if it becomes a problem, and if so then move them to an "unofficial" section in the body of the readme.  cc @zixuanzh

**Comment by ralexstokes** [comment]
ok -- sounds like we have support to merge this in then!

**Pull request merged**
