### PR TITLE
WIP - no duplicate addresses in peerdata

### PR DESCRIPTION
**Pull request by pacrob**
## What was wrong?

Updated from PR #325

## How was it fixed?

Summary of approach.

### To-Do

- [ ] Clean up commit history

* [ ] Add entry to the [release notes](https://github.com/libp2p/py-libp2p/blob/main/newsfragments/README.md)

#### Cute Animal Picture

image

### CODE REVIEW

**Comment by mystical-prog** [comment]
@pacrob I would like to contribute to this PR, as mentioned in #325 , I propose changing the data type of `addrs` from `List` to `Set`

**Comment by pacrob** [comment]
Go ahead, @mystical-prog , thanks! I had started adding the tests, as I realized there was nowhere to test whether there were duplicates or not.

**Comment by mystical-prog** [comment]
> Go ahead, @mystical-prog , thanks! I had started adding the tests, as I realized there was nowhere to test whether there were duplicates or not.

After doing detailed scoping, I realise that changing data type from List to Set will require lot of refactoring and is a breaking change, so I will suggest combine the changes from this PR and from #325

**Comment by pacrob** [comment]
closed by #485

**Pull request closed without merging**
